import {
  AnalysisResult,
  FindingItem,
  getSecurityGrade,
  getImpactNarrative,
  getMitreRefs,
  getOwaspRefs,
} from "./security";

// ===========================================================================
// Constants
// ===========================================================================

export const REPORT_TITLE = "Guardian AI Security Report" as const;
export const REPORT_GENERATOR = "Guardian AI Security Engineer" as const;

export const SECTION_EXECUTIVE_SUMMARY = "Executive Summary" as const;
export const SECTION_RISK_BREAKDOWN = "Risk Breakdown" as const;
export const SECTION_FINDINGS = "Findings" as const;
export const SECTION_SCAN_WARNINGS = "Scan Warnings" as const;

export const FRAMEWORK_MITRE = "MITRE ATT&CK" as const;
export const FRAMEWORK_OWASP = "OWASP Top 10" as const;

// ===========================================================================
// Helpers
// ===========================================================================

export function getTotalFindings(result: AnalysisResult): number {
  return (
    result.summary.critical +
    result.summary.high +
    result.summary.medium +
    result.summary.low
  );
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function buildReportFilename(
  repoLabel: string,
  extension: string,
): string {
  const date = new Date().toISOString().slice(0, 10);
  const slug = repoLabel
    .trim()
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  const safeSlug = slug || "repository";
  return `guardian-${safeSlug}-${date}.${extension}`;
}

// ===========================================================================
// Download
// ===========================================================================

export function downloadTextFile(
  filename: string,
  content: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.style.display = "none";
  document.body.appendChild(link);
  try {
    link.click();
  } finally {
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

// ===========================================================================
// Markdown Report
// ===========================================================================

export function buildMarkdownReport(
  result: AnalysisResult,
  repoLabel: string,
  scanDuration: string | null,
  completedAt: string | null,
): string {
  const grade = getSecurityGrade(result.risk.score);
  const totalFindings = getTotalFindings(result);
  const lines: string[] = [];

  // Title
  lines.push(`# ${REPORT_TITLE}`);
  lines.push("");

  // Metadata
  lines.push(`> Generated by ${REPORT_GENERATOR}`);
  lines.push(`>`);
  lines.push(`> **Repository:** ${repoLabel || "—"}`);
  lines.push(`> **Owner:** ${result.meta.owner || "—"}`);
  lines.push(`> **Branch:** ${result.meta.branch || "—"}`);
  lines.push(`> **Date:** ${completedAt ?? new Date().toISOString().slice(0, 10)}`);
  lines.push(`> **Files scanned:** ${result.meta.filesScanned}`);
  if (scanDuration) {
    lines.push(`> **Scan duration:** ${scanDuration}s`);
  }
  lines.push("");

  // Grade + score
  lines.push(`## Security Grade: ${grade.grade} (${grade.description})`);
  lines.push("");
  lines.push(`### Risk Score`);
  lines.push("");
  lines.push(`**${result.risk.score} / 100**`);
  lines.push("");

  // Executive Summary
  lines.push(`## ${SECTION_EXECUTIVE_SUMMARY}`);
  lines.push("");
  lines.push(
    `Guardian analyzed ${result.meta.filesScanned} file${result.meta.filesScanned === 1 ? "" : "s"} and detected ${totalFindings} security finding${totalFindings === 1 ? "" : "s"} (${result.summary.critical} critical, ${result.summary.high} high, ${result.summary.medium} medium, ${result.summary.low} low).`,
  );
  lines.push("");

  // Risk Breakdown
  lines.push(`## ${SECTION_RISK_BREAKDOWN}`);
  lines.push("");
  lines.push(`| Severity | Count |`);
  lines.push(`|---|---|`);
  lines.push(`| Critical | ${result.summary.critical} |`);
  lines.push(`| High | ${result.summary.high} |`);
  lines.push(`| Medium | ${result.summary.medium} |`);
  lines.push(`| Low | ${result.summary.low} |`);
  lines.push("");

  // Warnings
  if (result.warnings.length > 0) {
    lines.push(`## ${SECTION_SCAN_WARNINGS}`);
    lines.push("");
    result.warnings.forEach((warning) => lines.push(`- ${warning}`));
    lines.push("");
  }

  // Findings
  lines.push(`## ${SECTION_FINDINGS}`);
  lines.push("");

  if (result.findings.length === 0) {
    lines.push(
      "No exposed credentials, private keys, API keys, or environment files were detected.",
    );
  } else {
    result.findings.forEach((finding, index) => {
      const mitre = getMitreRefs(finding.type);
      const owasp = getOwaspRefs(finding.type);

      lines.push(
        `### ${index + 1}. ${finding.type} (${finding.severity.toUpperCase()})`,
      );
      lines.push("");
      lines.push(`**File:** \`${finding.file}:${finding.line}\``);
      lines.push("");
      lines.push(getImpactNarrative(finding.type));
      lines.push("");
      lines.push(
        `**${FRAMEWORK_MITRE}:** ${mitre.map((ref) => `${ref.id} (${ref.name})`).join(", ")}`,
      );
      lines.push("");
      lines.push(
        `**${FRAMEWORK_OWASP}:** ${owasp.map((ref) => `${ref.id} (${ref.name})`).join(", ")}`,
      );
      lines.push("");

      if (finding.investigation?.recommendation) {
        lines.push(
          `**Recommendation:** ${finding.investigation.recommendation}`,
        );
        lines.push("");
      }
      if (finding.verification) {
        lines.push(
          `**Verification:** ${finding.verification.status} — ${finding.verification.reason}`,
        );
        lines.push("");
      }
    });
  }

  return lines.join("\n");
}

// ===========================================================================
// Printable HTML Report
// ===========================================================================

function renderFinding(finding: FindingItem, index: number): string {
  const mitre = getMitreRefs(finding.type);
  const owasp = getOwaspRefs(finding.type);

  return `
      <div class="finding">
        <h3>${index + 1}. ${escapeHtml(finding.type)} — ${escapeHtml(finding.severity.toUpperCase())}</h3>
        <p class="mono">${escapeHtml(finding.file)}:${finding.line}</p>
        <p>${escapeHtml(getImpactNarrative(finding.type))}</p>
        <p><strong>${FRAMEWORK_MITRE}:</strong> ${mitre.map((ref) => `${ref.id} (${escapeHtml(ref.name)})`).join(", ")}</p>
        <p><strong>${FRAMEWORK_OWASP}:</strong> ${owasp.map((ref) => `${ref.id} (${escapeHtml(ref.name)})`).join(", ")}</p>
        ${finding.investigation?.recommendation ? `<p><strong>Recommendation:</strong> ${escapeHtml(finding.investigation.recommendation)}</p>` : ""}
        ${finding.verification ? `<p><strong>Verification:</strong> ${escapeHtml(finding.verification.status)} — ${escapeHtml(finding.verification.reason)}</p>` : ""}
      </div>`;
}

export function buildPrintableReportHtml(
  result: AnalysisResult,
  repoLabel: string,
  scanDuration: string | null,
  completedAt: string | null,
): string {
  const grade = getSecurityGrade(result.risk.score);
  const totalFindings = getTotalFindings(result);

  const findingsHtml =
    result.findings.length === 0
      ? "<p>No exposed credentials, private keys, API keys, or environment files were detected.</p>"
      : result.findings
          .map((finding, index) => renderFinding(finding, index))
          .join("");

  const warningsHtml =
    result.warnings.length > 0
      ? `
    <h2>${SECTION_SCAN_WARNINGS}</h2>
    <ul>${result.warnings.map((w) => `<li>${escapeHtml(w)}</li>`).join("")}</ul>`
      : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(REPORT_TITLE)}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #0c1511; margin: 40px; }
  h1 { margin-bottom: 4px; }
  .meta { color: #555; font-size: 13px; margin-bottom: 24px; line-height: 1.6; }
  .grade { font-size: 40px; font-weight: 700; }
  .grade-desc { font-size: 16px; font-weight: 500; }
  .score { margin-top: 4px; }
  table { border-collapse: collapse; margin: 16px 0; }
  td, th { border: 1px solid #ccc; padding: 6px 12px; text-align: left; font-size: 13px; }
  .finding { border-top: 1px solid #ddd; padding: 16px 0; }
  .mono { font-family: monospace; font-size: 12px; color: #555; }
  code { background: #f3f3f3; padding: 2px 4px; }
  h2 { margin-top: 32px; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }
  @media print {
    .finding { break-inside: avoid; }
    .footer { position: fixed; bottom: 0; left: 40px; right: 40px; }
  }
</style>
</head>
<body>
  <h1>${escapeHtml(REPORT_TITLE)}</h1>
  <p class="meta">
    Repository: ${escapeHtml(repoLabel || "—")}<br/>
    Owner: ${escapeHtml(result.meta.owner || "—")}<br/>
    Branch: ${escapeHtml(result.meta.branch || "—")}<br/>
    Scan completed: ${escapeHtml(completedAt ?? "—")} &nbsp;&middot;&nbsp; Duration: ${scanDuration ? `${escapeHtml(scanDuration)}s` : "—"} &nbsp;&middot;&nbsp; Files scanned: ${result.meta.filesScanned}
  </p>

  <div class="grade">${escapeHtml(grade.grade)} <span class="grade-desc">(${escapeHtml(grade.description)})</span></div>
  <p class="score">Risk Score: ${result.risk.score} / 100</p>

  <h2>${SECTION_EXECUTIVE_SUMMARY}</h2>
  <p>Guardian analyzed ${result.meta.filesScanned} file(s) and detected ${totalFindings} security finding(s) (${result.summary.critical} critical, ${result.summary.high} high, ${result.summary.medium} medium, ${result.summary.low} low).</p>

  <h2>${SECTION_RISK_BREAKDOWN}</h2>
  <table>
    <thead>
      <tr><th>Severity</th><th>Count</th></tr>
    </thead>
    <tbody>
      <tr><td>Critical</td><td>${result.summary.critical}</td></tr>
      <tr><td>High</td><td>${result.summary.high}</td></tr>
      <tr><td>Medium</td><td>${result.summary.medium}</td></tr>
      <tr><td>Low</td><td>${result.summary.low}</td></tr>
    </tbody>
  </table>

  <h2>${SECTION_FINDINGS}</h2>
  ${findingsHtml}
  ${warningsHtml}

  <div class="footer">Generated by ${escapeHtml(REPORT_GENERATOR)}</div>
</body>
</html>`;
}